#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK_ONLY=0
SKIP_RUNTIME=0
SKIP_VERIFY=0

for arg in "$@"; do
  case "$arg" in
    --check-only) CHECK_ONLY=1 ;;
    --skip-runtime-tools) SKIP_RUNTIME=1 ;;
    --skip-verification) SKIP_VERIFY=1 ;;
    *) echo "Bilinmeyen seçenek: $arg" >&2; exit 2 ;;
  esac
done

step() { printf '\n==> %s\n' "$1"; }
has() { command -v "$1" >/dev/null 2>&1; }

java_major() {
  local command_name="$1"
  if ! has "$command_name"; then echo 0; return; fi
  "$command_name" -version 2>&1 | awk -F'"' '/version/ { split($2, p, "."); print p[1]; exit }'
}

fail_check() {
  echo "$1 bulunamadı. Kurulum için ./setup.sh komutunu --check-only olmadan çalıştırın." >&2
  exit 1
}

install_dependencies() {
  local need_git="$1" need_java="$2" need_runtime="$3"
  if [[ "$CHECK_ONLY" == 1 ]]; then
    [[ "$need_git" == 0 ]] || fail_check Git
    [[ "$need_java" == 0 ]] || fail_check 'JDK 21'
    [[ "$need_runtime" == 0 ]] || fail_check 'yt-dlp/mpv'
    return
  fi

  if [[ "$(uname -s)" == Darwin ]]; then
    has brew || { echo "Homebrew bulunamadı: https://brew.sh adresinden kurup tekrar deneyin." >&2; exit 1; }
    [[ "$need_git" == 0 ]] || brew install git
    [[ "$need_java" == 0 ]] || brew install --cask temurin@21
    if [[ "$need_runtime" == 1 ]]; then brew install yt-dlp mpv; fi
    export JAVA_HOME="$(/usr/libexec/java_home -v 21)"
    export PATH="$JAVA_HOME/bin:$PATH"
  elif has apt-get; then
    local packages=(git openjdk-21-jdk)
    [[ "$need_runtime" == 0 ]] || packages+=(yt-dlp mpv)
    sudo apt-get update
    sudo apt-get install -y "${packages[@]}" || { echo 'APT kurulumu başarısız. Git, OpenJDK 21, yt-dlp ve mpv paketlerini dağıtımınızın belgelerine göre kurun.' >&2; exit 1; }
  elif has dnf; then
    local packages=(git java-21-openjdk-devel)
    [[ "$need_runtime" == 0 ]] || packages+=(yt-dlp mpv)
    sudo dnf install -y "${packages[@]}"
  elif has pacman; then
    local packages=(git jdk21-openjdk)
    [[ "$need_runtime" == 0 ]] || packages+=(yt-dlp mpv)
    sudo pacman -S --needed --noconfirm "${packages[@]}"
  elif has zypper; then
    local packages=(git java-21-openjdk-devel)
    [[ "$need_runtime" == 0 ]] || packages+=(yt-dlp mpv)
    sudo zypper --non-interactive install "${packages[@]}"
  else
    echo 'Desteklenen paket yöneticisi bulunamadı. Git, JDK 21, yt-dlp ve mpv kurup tekrar deneyin.' >&2
    exit 1
  fi
}

echo 'PocketTune geliştirme ortamı hazırlanıyor.'
need_git=0; has git || need_git=1
need_java=0
if [[ "$(java_major java)" != 21 || "$(java_major javac)" != 21 ]]; then need_java=1; fi
need_runtime=0
if [[ "$SKIP_RUNTIME" == 0 ]] && { ! has yt-dlp || ! has mpv; }; then need_runtime=1; fi
install_dependencies "$need_git" "$need_java" "$need_runtime"

has git || { echo 'Git etkinleştirilemedi.' >&2; exit 1; }
[[ "$(java_major java)" == 21 && "$(java_major javac)" == 21 ]] || { echo 'JDK 21 etkinleştirilemedi.' >&2; exit 1; }

yt_dlp=''; mpv_path=''
if [[ "$SKIP_RUNTIME" == 0 ]]; then
  yt_dlp="$(command -v yt-dlp)"
  mpv_path="$(command -v mpv)"
  if [[ "$CHECK_ONLY" == 0 ]]; then
    for game_dir in run run-client; do
      mkdir -p "$ROOT/$game_dir/config"
      cat > "$ROOT/$game_dir/config/pockettune-common.toml" <<EOF
# Generated by scripts/setup-dev.sh for this ignored development game directory.
[externalTools]
ytDlpPathOverride = "$yt_dlp"
mpvPathOverride = "$mpv_path"
EOF
    done
  fi
fi

step 'Araç sürümleri'
git --version
java -version
[[ -z "$yt_dlp" ]] || "$yt_dlp" --version
[[ -z "$mpv_path" ]] || "$mpv_path" --version --no-config | head -n 1

if [[ "$CHECK_ONLY" == 0 && "$SKIP_VERIFY" == 0 ]]; then
  step 'JUnit doğrulaması çalıştırılıyor (Minecraft açılmaz)'
  (cd "$ROOT" && ./gradlew test --no-daemon --no-configuration-cache)
fi

printf '\nPocketTune geliştirme ortamı hazır.\n'
echo 'Derleme: ./gradlew clean build --no-daemon'
