[CmdletBinding()]
param(
    [switch]$CheckOnly,
    [switch]$SkipRuntimeTools,
    [switch]$SkipVerification
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot

function Write-Step([string]$Message) {
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

function Refresh-ProcessPath {
    $machine = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $user = [Environment]::GetEnvironmentVariable('Path', 'User')
    $env:Path = @($machine, $user) -join [IO.Path]::PathSeparator
}

function Resolve-Winget {
    $command = Get-Command winget.exe -ErrorAction SilentlyContinue
    if ($command) { return $command.Source }
    $fallback = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps\winget.exe'
    if (Test-Path -LiteralPath $fallback) { return $fallback }
    return $null
}

function Install-WingetPackage([string]$Id, [string]$Label) {
    if ($CheckOnly) {
        throw "$Label is missing. Run setup.ps1 without -CheckOnly to install it."
    }
    $winget = Resolve-Winget
    if (-not $winget) {
        throw "Microsoft WinGet is missing. Install 'App Installer' from Microsoft Store, then run setup.ps1 again."
    }
    Write-Step "Installing $Label"
    & $winget install --id $Id --exact --accept-package-agreements --accept-source-agreements --disable-interactivity
    if ($LASTEXITCODE -ne 0) { throw "$Label installation failed (WinGet exit code: $LASTEXITCODE)." }
    Refresh-ProcessPath
}

function Get-JavaMajor([string]$CommandName) {
    $java = Get-Command $CommandName -ErrorAction SilentlyContinue
    if (-not $java) { return 0 }
    $versionText = (& $java.Source --version 2>&1 | Out-String)
    if ($versionText -match '(?m)^(?:java|javac)(?:\s+version)?\s+"?(?<major>\d+)') {
        return [int]$Matches.major
    }
    return 0
}

function Resolve-Executable([string]$Name) {
    $command = Get-Command "$Name.exe" -ErrorAction SilentlyContinue
    if ($command) { return $command.Source }

    $packages = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages'
    if (Test-Path -LiteralPath $packages) {
        $match = Get-ChildItem -LiteralPath $packages -Filter "$Name.exe" -File -Recurse -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($match) { return $match.FullName }
    }
    return $null
}

function Set-JavaHome {
    $java = Get-Command java.exe -ErrorAction Stop
    $javaHome = Split-Path -Parent (Split-Path -Parent $java.Source)
    if ((Test-Path -LiteralPath (Join-Path $javaHome 'bin\javac.exe')) -and -not $CheckOnly) {
        [Environment]::SetEnvironmentVariable('JAVA_HOME', $javaHome, 'User')
        $env:JAVA_HOME = $javaHome
    }
}

function Escape-Toml([string]$Value) {
    return $Value.Replace('\', '/').Replace('"', '\"')
}

function Write-DevelopmentConfig([string]$GameDirectory, [string]$YtDlp, [string]$Mpv) {
    $configDirectory = Join-Path $Root "$GameDirectory\config"
    New-Item -ItemType Directory -Force -Path $configDirectory | Out-Null
    $target = Join-Path $configDirectory 'pockettune-common.toml'
    $contents = @"
# Generated by scripts/setup-dev.ps1 for this ignored development game directory.
[externalTools]
ytDlpPathOverride = "$(Escape-Toml $YtDlp)"
mpvPathOverride = "$(Escape-Toml $Mpv)"
"@
    [IO.File]::WriteAllText($target, $contents + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))
}

Write-Host 'Preparing the PocketTune development environment.' -ForegroundColor Green
Refresh-ProcessPath

if (-not (Get-Command git.exe -ErrorAction SilentlyContinue)) {
    Install-WingetPackage 'Git.Git' 'Git'
}

if ((Get-JavaMajor 'java.exe') -ne 21 -or (Get-JavaMajor 'javac.exe') -ne 21) {
    Install-WingetPackage 'EclipseAdoptium.Temurin.21.JDK' 'Temurin JDK 21'
}
if ((Get-JavaMajor 'java.exe') -ne 21 -or (Get-JavaMajor 'javac.exe') -ne 21) {
    throw 'JDK 21 could not be activated. Check JAVA_HOME and PATH.'
}
Set-JavaHome

$ytDlp = $null
$mpv = $null
if (-not $SkipRuntimeTools) {
    $ytDlp = Resolve-Executable 'yt-dlp'
    if (-not $ytDlp) {
        Install-WingetPackage 'yt-dlp.yt-dlp' 'yt-dlp'
        $ytDlp = Resolve-Executable 'yt-dlp'
    }

    $mpv = Resolve-Executable 'mpv'
    if (-not $mpv) {
        Install-WingetPackage 'mpv-player.mpv-CI.MSVC' 'mpv'
        $mpv = Resolve-Executable 'mpv'
    }

    if (-not $ytDlp -or -not $mpv) { throw 'yt-dlp or mpv was not found after installation. Open a new terminal and try again.' }
    if (-not $CheckOnly) {
        Write-Step 'Writing local development configuration'
        Write-DevelopmentConfig 'run' $ytDlp $mpv
        Write-DevelopmentConfig 'run-client' $ytDlp $mpv
    }
}

Write-Step 'Tool versions'
git --version
java --version
if ($ytDlp) { & $ytDlp --version }
if ($mpv) { & $mpv --version --no-config | Select-Object -First 1 }

if (-not $CheckOnly -and -not $SkipVerification) {
    Write-Step 'Running JUnit verification (Minecraft will not start)'
    Push-Location $Root
    try {
        & .\gradlew.bat test --no-daemon --no-configuration-cache
        if ($LASTEXITCODE -ne 0) { throw "Gradle tests failed (exit code: $LASTEXITCODE)." }
    } finally {
        Pop-Location
    }
}

Write-Host "`nPocketTune development environment is ready." -ForegroundColor Green
Write-Host 'Build: .\gradlew.bat clean build --no-daemon'
